zookeeper:
  image: jplock/zookeeper:3.4.6
  name: zookeeper
  ports:
    - "2181:2181"
    - "2888:2888"
    - "3888:3888"
etcd:
  image: quay.io/coreos/etcd:v2.1.1
  name: etcd
  volumes:
    - /etc/ssl/certs:/etc/ssl/certs
  ports:
    - "2379:2379"
    - "2380:2380"
    - "4001:4001"
    - "7001:7001"
  environment:
    ETCD_NAME: etcd0
    ETCD_ADVERTISE_CLIENT_URLS: http://192.168.99.100:2379,http://192.168.99.100:4001
    ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379,http://0.0.0.0:4001
    ETCD_INITIAL_ADVERTISE_PEER_URLS: http://192.168.99.100:2380
    ETCD_LISTEN_PEERS_URLS: http://0.0.0.0:2380,http://0.0.0.0:7001
    ETCD_INITIAL_CLUSTER_TOKEN: etcd-cluster-1
    ETCD_INITIAL_CLUSTER: etcd0=http://192.168.99.100:2380
    ETCD_INITIAL_CLUSTER_STATE: new